// Code generated by counterfeiter. DO NOT EDIT.
package watcherfakes

import (
	"sync"

	"github.com/hcjulz/damon/models"
	"github.com/hcjulz/damon/watcher"
)

type FakePrometheusClient struct {
	ClusterUtilizationStub        func() (*models.ResourceUtilization, error)
	clusterUtilizationMutex       sync.RWMutex
	clusterUtilizationArgsForCall []struct {
	}
	clusterUtilizationReturns struct {
		result1 *models.ResourceUtilization
		result2 error
	}
	clusterUtilizationReturnsOnCall map[int]struct {
		result1 *models.ResourceUtilization
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePrometheusClient) ClusterUtilization() (*models.ResourceUtilization, error) {
	fake.clusterUtilizationMutex.Lock()
	ret, specificReturn := fake.clusterUtilizationReturnsOnCall[len(fake.clusterUtilizationArgsForCall)]
	fake.clusterUtilizationArgsForCall = append(fake.clusterUtilizationArgsForCall, struct {
	}{})
	stub := fake.ClusterUtilizationStub
	fakeReturns := fake.clusterUtilizationReturns
	fake.recordInvocation("ClusterUtilization", []interface{}{})
	fake.clusterUtilizationMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrometheusClient) ClusterUtilizationCallCount() int {
	fake.clusterUtilizationMutex.RLock()
	defer fake.clusterUtilizationMutex.RUnlock()
	return len(fake.clusterUtilizationArgsForCall)
}

func (fake *FakePrometheusClient) ClusterUtilizationCalls(stub func() (*models.ResourceUtilization, error)) {
	fake.clusterUtilizationMutex.Lock()
	defer fake.clusterUtilizationMutex.Unlock()
	fake.ClusterUtilizationStub = stub
}

func (fake *FakePrometheusClient) ClusterUtilizationReturns(result1 *models.ResourceUtilization, result2 error) {
	fake.clusterUtilizationMutex.Lock()
	defer fake.clusterUtilizationMutex.Unlock()
	fake.ClusterUtilizationStub = nil
	fake.clusterUtilizationReturns = struct {
		result1 *models.ResourceUtilization
		result2 error
	}{result1, result2}
}

func (fake *FakePrometheusClient) ClusterUtilizationReturnsOnCall(i int, result1 *models.ResourceUtilization, result2 error) {
	fake.clusterUtilizationMutex.Lock()
	defer fake.clusterUtilizationMutex.Unlock()
	fake.ClusterUtilizationStub = nil
	if fake.clusterUtilizationReturnsOnCall == nil {
		fake.clusterUtilizationReturnsOnCall = make(map[int]struct {
			result1 *models.ResourceUtilization
			result2 error
		})
	}
	fake.clusterUtilizationReturnsOnCall[i] = struct {
		result1 *models.ResourceUtilization
		result2 error
	}{result1, result2}
}

func (fake *FakePrometheusClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePrometheusClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ watcher.PrometheusClient = new(FakePrometheusClient)
