// Code generated by counterfeiter. DO NOT EDIT.
package nomadfakes

import (
	"sync"

	"github.com/hcjulz/damon/nomad"
)

type FakeStatusClient struct {
	LeaderStub        func() (string, error)
	leaderMutex       sync.RWMutex
	leaderArgsForCall []struct {
	}
	leaderReturns struct {
		result1 string
		result2 error
	}
	leaderReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStatusClient) Leader() (string, error) {
	fake.leaderMutex.Lock()
	ret, specificReturn := fake.leaderReturnsOnCall[len(fake.leaderArgsForCall)]
	fake.leaderArgsForCall = append(fake.leaderArgsForCall, struct {
	}{})
	stub := fake.LeaderStub
	fakeReturns := fake.leaderReturns
	fake.recordInvocation("Leader", []interface{}{})
	fake.leaderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStatusClient) LeaderCallCount() int {
	fake.leaderMutex.RLock()
	defer fake.leaderMutex.RUnlock()
	return len(fake.leaderArgsForCall)
}

func (fake *FakeStatusClient) LeaderCalls(stub func() (string, error)) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = stub
}

func (fake *FakeStatusClient) LeaderReturns(result1 string, result2 error) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = nil
	fake.leaderReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStatusClient) LeaderReturnsOnCall(i int, result1 string, result2 error) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = nil
	if fake.leaderReturnsOnCall == nil {
		fake.leaderReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.leaderReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStatusClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStatusClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ nomad.StatusClient = new(FakeStatusClient)
