// Code generated by counterfeiter. DO NOT EDIT.
package nomadfakes

import (
	"sync"

	"github.com/hashicorp/nomad/api"
	"github.com/hcjulz/damon/nomad"
)

type FakeAgentClient struct {
	MembersStub        func() (*api.ServerMembers, error)
	membersMutex       sync.RWMutex
	membersArgsForCall []struct {
	}
	membersReturns struct {
		result1 *api.ServerMembers
		result2 error
	}
	membersReturnsOnCall map[int]struct {
		result1 *api.ServerMembers
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAgentClient) Members() (*api.ServerMembers, error) {
	fake.membersMutex.Lock()
	ret, specificReturn := fake.membersReturnsOnCall[len(fake.membersArgsForCall)]
	fake.membersArgsForCall = append(fake.membersArgsForCall, struct {
	}{})
	stub := fake.MembersStub
	fakeReturns := fake.membersReturns
	fake.recordInvocation("Members", []interface{}{})
	fake.membersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAgentClient) MembersCallCount() int {
	fake.membersMutex.RLock()
	defer fake.membersMutex.RUnlock()
	return len(fake.membersArgsForCall)
}

func (fake *FakeAgentClient) MembersCalls(stub func() (*api.ServerMembers, error)) {
	fake.membersMutex.Lock()
	defer fake.membersMutex.Unlock()
	fake.MembersStub = stub
}

func (fake *FakeAgentClient) MembersReturns(result1 *api.ServerMembers, result2 error) {
	fake.membersMutex.Lock()
	defer fake.membersMutex.Unlock()
	fake.MembersStub = nil
	fake.membersReturns = struct {
		result1 *api.ServerMembers
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentClient) MembersReturnsOnCall(i int, result1 *api.ServerMembers, result2 error) {
	fake.membersMutex.Lock()
	defer fake.membersMutex.Unlock()
	fake.MembersStub = nil
	if fake.membersReturnsOnCall == nil {
		fake.membersReturnsOnCall = make(map[int]struct {
			result1 *api.ServerMembers
			result2 error
		})
	}
	fake.membersReturnsOnCall[i] = struct {
		result1 *api.ServerMembers
		result2 error
	}{result1, result2}
}

func (fake *FakeAgentClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAgentClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ nomad.AgentClient = new(FakeAgentClient)
