// Code generated by counterfeiter. DO NOT EDIT.
package nomadfakes

import (
	"context"
	"io"
	"sync"

	"github.com/hashicorp/nomad/api"
	"github.com/hcjulz/damon/nomad"
)

type FakeAllocationsClient struct {
	ExecStub        func(context.Context, *api.Allocation, string, bool, []string, io.Reader, io.Writer, io.Writer, <-chan api.TerminalSize, *api.QueryOptions) (int, error)
	execMutex       sync.RWMutex
	execArgsForCall []struct {
		arg1  context.Context
		arg2  *api.Allocation
		arg3  string
		arg4  bool
		arg5  []string
		arg6  io.Reader
		arg7  io.Writer
		arg8  io.Writer
		arg9  <-chan api.TerminalSize
		arg10 *api.QueryOptions
	}
	execReturns struct {
		result1 int
		result2 error
	}
	execReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	InfoStub        func(string, *api.QueryOptions) (*api.Allocation, *api.QueryMeta, error)
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
		arg1 string
		arg2 *api.QueryOptions
	}
	infoReturns struct {
		result1 *api.Allocation
		result2 *api.QueryMeta
		result3 error
	}
	infoReturnsOnCall map[int]struct {
		result1 *api.Allocation
		result2 *api.QueryMeta
		result3 error
	}
	ListStub        func(*api.QueryOptions) ([]*api.AllocationListStub, *api.QueryMeta, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		arg1 *api.QueryOptions
	}
	listReturns struct {
		result1 []*api.AllocationListStub
		result2 *api.QueryMeta
		result3 error
	}
	listReturnsOnCall map[int]struct {
		result1 []*api.AllocationListStub
		result2 *api.QueryMeta
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAllocationsClient) Exec(arg1 context.Context, arg2 *api.Allocation, arg3 string, arg4 bool, arg5 []string, arg6 io.Reader, arg7 io.Writer, arg8 io.Writer, arg9 <-chan api.TerminalSize, arg10 *api.QueryOptions) (int, error) {
	var arg5Copy []string
	if arg5 != nil {
		arg5Copy = make([]string, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.execMutex.Lock()
	ret, specificReturn := fake.execReturnsOnCall[len(fake.execArgsForCall)]
	fake.execArgsForCall = append(fake.execArgsForCall, struct {
		arg1  context.Context
		arg2  *api.Allocation
		arg3  string
		arg4  bool
		arg5  []string
		arg6  io.Reader
		arg7  io.Writer
		arg8  io.Writer
		arg9  <-chan api.TerminalSize
		arg10 *api.QueryOptions
	}{arg1, arg2, arg3, arg4, arg5Copy, arg6, arg7, arg8, arg9, arg10})
	stub := fake.ExecStub
	fakeReturns := fake.execReturns
	fake.recordInvocation("Exec", []interface{}{arg1, arg2, arg3, arg4, arg5Copy, arg6, arg7, arg8, arg9, arg10})
	fake.execMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAllocationsClient) ExecCallCount() int {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return len(fake.execArgsForCall)
}

func (fake *FakeAllocationsClient) ExecCalls(stub func(context.Context, *api.Allocation, string, bool, []string, io.Reader, io.Writer, io.Writer, <-chan api.TerminalSize, *api.QueryOptions) (int, error)) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = stub
}

func (fake *FakeAllocationsClient) ExecArgsForCall(i int) (context.Context, *api.Allocation, string, bool, []string, io.Reader, io.Writer, io.Writer, <-chan api.TerminalSize, *api.QueryOptions) {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	argsForCall := fake.execArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7, argsForCall.arg8, argsForCall.arg9, argsForCall.arg10
}

func (fake *FakeAllocationsClient) ExecReturns(result1 int, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	fake.execReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAllocationsClient) ExecReturnsOnCall(i int, result1 int, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	if fake.execReturnsOnCall == nil {
		fake.execReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.execReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAllocationsClient) Info(arg1 string, arg2 *api.QueryOptions) (*api.Allocation, *api.QueryMeta, error) {
	fake.infoMutex.Lock()
	ret, specificReturn := fake.infoReturnsOnCall[len(fake.infoArgsForCall)]
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
		arg1 string
		arg2 *api.QueryOptions
	}{arg1, arg2})
	stub := fake.InfoStub
	fakeReturns := fake.infoReturns
	fake.recordInvocation("Info", []interface{}{arg1, arg2})
	fake.infoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAllocationsClient) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *FakeAllocationsClient) InfoCalls(stub func(string, *api.QueryOptions) (*api.Allocation, *api.QueryMeta, error)) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = stub
}

func (fake *FakeAllocationsClient) InfoArgsForCall(i int) (string, *api.QueryOptions) {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	argsForCall := fake.infoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAllocationsClient) InfoReturns(result1 *api.Allocation, result2 *api.QueryMeta, result3 error) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	fake.infoReturns = struct {
		result1 *api.Allocation
		result2 *api.QueryMeta
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAllocationsClient) InfoReturnsOnCall(i int, result1 *api.Allocation, result2 *api.QueryMeta, result3 error) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	if fake.infoReturnsOnCall == nil {
		fake.infoReturnsOnCall = make(map[int]struct {
			result1 *api.Allocation
			result2 *api.QueryMeta
			result3 error
		})
	}
	fake.infoReturnsOnCall[i] = struct {
		result1 *api.Allocation
		result2 *api.QueryMeta
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAllocationsClient) List(arg1 *api.QueryOptions) ([]*api.AllocationListStub, *api.QueryMeta, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		arg1 *api.QueryOptions
	}{arg1})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{arg1})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAllocationsClient) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeAllocationsClient) ListCalls(stub func(*api.QueryOptions) ([]*api.AllocationListStub, *api.QueryMeta, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeAllocationsClient) ListArgsForCall(i int) *api.QueryOptions {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	argsForCall := fake.listArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAllocationsClient) ListReturns(result1 []*api.AllocationListStub, result2 *api.QueryMeta, result3 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 []*api.AllocationListStub
		result2 *api.QueryMeta
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAllocationsClient) ListReturnsOnCall(i int, result1 []*api.AllocationListStub, result2 *api.QueryMeta, result3 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 []*api.AllocationListStub
			result2 *api.QueryMeta
			result3 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 []*api.AllocationListStub
		result2 *api.QueryMeta
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAllocationsClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAllocationsClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ nomad.AllocationsClient = new(FakeAllocationsClient)
